### ISSUE TITLE
自分でコードを借りて使用しようとしてるのですがBOTが動きませんんAPIの場所ってここでいいのでしょうか

### ISSUE THREAD

**Issue by aki0429** [minty1202/line-bot-train#15]
scheduler.rake
このファイルのAPIの欄を変更したのですができません
これは自動でプログラムが起動するのでしょうかそれとも常に起動させるプログラムがあるのでしょうか？
実はプログラミング関係触るのが初めてお手柔らかにおおしえいただけないでしょうか？
大変恐縮ですが宜しくお願い致します

**Comment by minty1202** [comment]
質問ありがとうございます
ご自身の開発環境で動かす場合line devにアプリを登録してから外部接続していただくのがいいかと思います。

以下サイトに登録
https://developers.line.biz/ja/

line developersのコンソールに移動するとプロバイダーの欄があると思います

プロバイダーの作成からプロバイダーを作成してください
![image](https://user-images.githubusercontent.com/62473570/167330435-ad57004b-3df1-4bb4-93ba-722b12b38b49.png)

message api を選択して必要項目を埋めてチャンネルを作成

.envファイルを作成してそのファイルに
```env
LINE_CHANNEL_SECRET=チャンネルシークレットのトークン
LINE_CHANNEL_TOKEN=チャンネルアクセストークン
```

を記述してください



rails s をしてngrok等を使用して外部公開
https://qiita.com/mininobu/items/b45dbc70faedf30f484e

チャンネルのwebhookurlを外部公開したurlを記述

この状態までして

`rake send_train_message`

コマンドを実行していただければ返答が来ると思います

**Comment by aki0429** [comment]
VPSのストレージにファイルをおいてるのですがそれではできないのでしょうか？
ちなみに今時点でこんなエラーが出ます
お忙しいところ失礼いたしますが宜しくお願い致します

`$ rake send_train_message
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/shdcrentSV-User/.local/share/gem/ruby/gems/rake-13.0.6/exe/rake:27:in ｀<top (required)>｀
(See full trace by running task with --trace)`

**Comment by minty1202** [comment]
ファイル自体はVPSに置いていても実行できると思います。
純粋にlineから返答する環境がないため正常に動作していないです。

申し訳ないことにaki0429さんの変更内容を本番環境に反映させるわけにはいかないためline developerからテスト用のチャンネルを作成していただく必要があります。

**Comment by aki0429** [comment]
lineのAPIは記載してますがどこかおかしいのでしょうか？

`config.channel_secret = ENV["LINE_CHANNEL_SECRET"]`　にチャンネルシークレットを
` config.channel_token = ENV["LINE_CHANNEL_TOKEN"]`　にチャネルアクセストークン（長期）を記載すればいいんですよね（”ここに記載”）
ですがなぜか動きません

**Comment by minty1202** [comment]
実行するディレクトリの階層がおかしい可能性はありませんか？

**Comment by aki0429** [comment]
ユーザーの下にフォルダー（lineBOTのすべての）がありますね

**Comment by minty1202** [comment]
コマンドはユーザーではなくフォルダがある場所で行っていますか？

**Comment by aki0429** [comment]
サーバーの名前が書いてあります

**Comment by aki0429** [comment]
`Gemfile` のパースでエラーが発生しました。Gemfile のローカル変数またはメソッド `urce' が未定義です。Bundler は続行できません。
っていわれました

**Comment by aki0429** [comment]
`rake send_train_message
(in /home/shdcrentSV-User/line-bot-train)
Could not find rails-6.1.4.1, pg-1.2.3, puma-5.4.0, bootsnap-1.8.1, byebug-11.1.3, listen-3.7.0, dotenv-rails-2.7.6, rails-i18n-6.0.0, actioncable-6.1.4.1, actionmailbox-6.1.4.1, actiontext-6.1.4.1, nio4r-2.5.8, msgpack-1.4.2, rb-inotify-0.10.1, websocket-driver-0.7.5, nokogiri-1.12.3, ffi-1.15.3, mini_portile2-2.6.1 in any of the sources
Run (bundle install) to install missing gems.`

との記載があり実行してもここに戻ってしまいます

**Comment by aki0429** [comment]
何度もすいません

上の前にこんな事があったので
書き換えしてみて上のようになりました

rake send_train_message
(/home/shdcrentSV-User/line-bot-train にあります)
Ruby のバージョンは 3.0.4 ですが、Gemfile には 2.7.1 が指定されています。

**Comment by minty1202** [comment]
私の今回構築したアプリはruby 2.7.1で作っているので書き換えていただくか、vps上のruby環境を変えてください
お話を聞いているとファイル等の問題ではなくvps で railsを動かす準備ができていないように感じます。
rails vps 等で調べてみてください
